name: flutter_pos_sqlite
description: A new Flutter project.

# Menambahkan blok ini untuk memperbaiki error
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sqflite: ^2.3.3
  path: ^1.9.0
  intl: ^0.19.0
  crypto: ^3.0.3

# ... sisa file Anda